// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers"; // Import ini

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Event Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Bungkus children di sini */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
